name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Git
        uses: actions/checkout@v3

      - name: Setup Node.js environment      
        uses: actions/setup-node@v4.0.2
    
      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: latest

      - name: Install Node Packages
        run: pnpm i
      
      - name: Build
        run: pnpm build -q -p
      
      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "dist/*.zip"
          bodyFile: "dist/patch_notes.txt"
          makeLatest: true

      - name: Upload to Mod Portal
        uses: lisekilis/Factorio-mod-portal-Upload@v1.0.0
        env:
          FACTORIO_API_TOKEN: ${{ secrets.FACTORIO_TOKEN }}